export const environment = {
  production: true,
  appName: 'InnoWee',
    apiEndpoint: 'https://innoweee.platform.smartcommunitylab.it/innoweee-engine/',
    getDomainApi: 'api/profile',
    getInstituteApi: 'api/institute',
    getSchoolApi: 'api/school',
    getGameApi: 'api/game/',
    getPlayerApi: 'api/player',
    getMaterialApi:'/link',
    getCatalogApi:'api/catalog',
    getCollection: 'api/collection/',
    buyComponentApi:'/buy/',
    contributionApi:'/contribution/',
    robotApi:"/robot/",
    getRobotImageApi:"api/image/robot/",
    getItemApi:"api/item",
    getReduceApi:"/reduce",
    itemSocketURL:"itemws",
    getDeliveryApi:"/delivery",
    getGarbageApi:"api/garbageMap/",
    getUsedApi:"/used",
    aacClientId: "2c53f587-693c-48fa-b579-65506d8d3221",
    redirectUrl: 'https://innoweee.platform.smartcommunitylab.it/',
    scope: 'openid profile email profile.basicprofile.me',
    aacUrl: 'https://aac.platform.smartcommunitylab.it/aac/'
};
