
export const environment = {
  production: true,
  apiEndpoint: "undefined",
    getDomainApi: "undefined",
    getInstituteApi: "undefined",
    getSchoolApi: "undefined",
    getGameApi: "undefined",
    getPlayerApi: "undefined",
    getMaterialApi: "undefined",
    getCatalogApi: "undefined",
    getCollection: "undefined",
    buyComponentApi: "undefined",
    contributionApi: "undefined",
    robotApi: "undefined",
    getRobotImageApi: "undefined",
    getItemApi: "undefined",
    getReduceApi: "undefined",
    itemSocketURL: "undefined",
    getDeliveryApi: "undefined",
    getGarbageApi: "undefined",
    getUsedApi: "undefined",
    aacClientId: "undefined",
    redirectUrl: "undefined",
    scope: "undefined",
    aacUrl: "undefined",
  superSecretKey: "undefined",
  superDoubleSecret: "undefined" 
};
